-- 코드를 작성해주세요
SELECT COUNT(INFO.FISH_TYPE) AS FISH_COUNT, NAME_INFO.FISH_NAME 
FROM FISH_INFO AS INFO
JOIN FISH_NAME_INFO AS NAME_INFO
ON INFO.FISH_TYPE = NAME_INFO.FISH_TYPE 
GROUP BY NAME_INFO.FISH_NAME -- 이름을 기준으로 하기 때문에 FISH_COUNT GROUP BY가 아닌 FISH_NAME를 묶어준다
ORDER BY FISH_COUNT DESC;